version: '3.8'

services:
  emqx:
    image: emqx/emqx:latest
    container_name: TTS_EMQX
    environment:
      - EMQX_NAME=emqx
      - EMQX_HOST=127.0.0.1
    network_mode: "host"

  web:
    build: .
    container_name: TTS_DJANGO_WEB
    command: >
      bash -c "wait-for-it ${DJANGO_DB_HOST}:${DJANGO_DB_PORT} --timeout=30 -- bash -c 'wait-for-it emqx:18083 --timeout=30 -- python manage.py makemigrations --noinput &&
                   python manage.py migrate --noinput &&
                   python manage.py loaddata initial_load.json &&
                   python manage.py runserver 0.0.0.0:8000'"
    volumes:
      - .:/app
    depends_on:
      - emqx
    environment:
      - DJANGO_DB_USER=${DJANGO_DB_USER}
      - DJANGO_DB_PASSWORD=${DJANGO_DB_PASSWORD}
      - DJANGO_DB_NAME=${DJANGO_DB_NAME}
      - DJANGO_DB_HOST=${DJANGO_DB_HOST}
      - DJANGO_DB_PORT=${DJANGO_DB_PORT}
    network_mode: "host"
