version: '3.8'

services:
  emqx:
    image: emqx/emqx:latest
    container_name: TTS_EMQX
    environment:
      - EMQX_NAME=emqx
      - EMQX_HOST=127.0.0.1
    network_mode: "host"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:18083/status"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      network: host
    container_name: TTS_DJANGO_WEB
    command: >
      bash -c "
        wait-for-it ${DJANGO_DB_HOST}:${DJANGO_DB_PORT} --timeout=30 -- \
        bash -c 'wait-for-it 127.0.0.1:18083 --timeout=30 -- \
        python manage.py makemigrations --noinput &&
        python manage.py migrate --noinput &&
        if [ -f initial_load.json ]; then python manage.py loaddata initial_load.json; else echo \"[INFO] initial_load.json niet gevonden, overslaan\"; fi &&
        python manage.py runserver 0.0.0.0:8000'"
    volumes:
      - .:/app
    depends_on:
      emqx:
        condition: service_healthy
    environment:
      - DB=jdbc:postgresql://localhost:5432/django_db
      - DJANGO_DB_USER=${DJANGO_DB_USER}
      - DJANGO_DB_PASSWORD=${DJANGO_DB_PASSWORD}
      - DJANGO_DB_NAME=${DJANGO_DB_NAME}
      - DJANGO_DB_HOST=${DJANGO_DB_HOST}
      - DJANGO_DB_PORT=${DJANGO_DB_PORT}
    network_mode: host
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8000"]
      interval: 10s
      timeout: 5s
      retries: 5
