# Generated by Django 5.1.7 on 2025-05-05 11:46

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('area', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, geography=True, null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('screen_name', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
                ('ais_type', models.CharField(blank=True, max_length=255, null=True)),
                ('ais_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ais_callsign', models.CharField(blank=True, max_length=255, null=True)),
                ('ais_length', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)])),
                ('ais_width', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)])),
                ('adsb_type', models.CharField(blank=True, max_length=255, null=True)),
                ('adsb_registration', models.CharField(blank=True, max_length=255, null=True)),
                ('adsb_callsign', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, default=0, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('altitude', models.FloatField(blank=True, default=0, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('position_timestamp', models.BigIntegerField(blank=True, help_text='UNIX tijd in milliseconden (UTC)', null=True)),
                ('position', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('groups', models.ManyToManyField(blank=True, related_name='trackers', to='data.trackergroup')),
            ],
        ),
        migrations.CreateModel(
            name='TrackerIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255)),
                ('identifier_type', models.CharField(max_length=255)),
                ('identkey', models.CharField(editable=False, max_length=255, unique=True)),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='data.tracker')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField()),
                ('created_at', models.BigIntegerField(help_text='UNIX tijd in milliseconden (UTC)')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('sha256_key', models.CharField(blank=True, max_length=64, null=True)),
                ('tracker_identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='data.trackeridentifier')),
            ],
        ),
    ]
