# Generated by Django 5.1.7 on 2025-05-05 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_trackeridentifiertype_trackergroup_visible_fields_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='location',
            new_name='position',
        ),
    ]
